# Generated by Django 5.2.7 on 2025-12-13 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_telegramuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch', to=settings.AUTH_USER_MODEL),
        ),
    ]
