# Generated by Django 5.2.7 on 2025-12-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
