# Generated by Django 5.2.7 on 2026-01-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresetcode_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='brainch_id',
            new_name='branch_id',
        ),
    ]
