# Generated by Django 5.2.7 on 2026-02-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_brainch_id_branch_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
