# Generated by Django 5.2.7 on 2026-02-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_telegramuser_language_code_telegramuser_photo_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
