# Generated by Django 5.2.5 on 2025-08-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_branch_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
    ]
