# Generated by Django 5.2.5 on 2025-08-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('products', '0005_disease_state_diseasecategory_state_product_state_and_more'),
        ('users', '0006_branch_state_telegramuser_state_user_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='products.productsku'),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('QUESTION', 'Question'), ('ANSWER', 'Answer')], default='QUESTION'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='users.telegramuser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('UNREAD', 'Unread'), ('NEW', 'New'), ('UNREPLIED', 'Unreplied'), ('REPLIED', 'Replied')], default='UNREAD'),
        ),
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chats.topic'),
        ),
    ]
