# Generated by Django 5.2.7 on 2025-11-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
        ('products', '0003_alter_diseasecategory_options_alter_disease_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='diseases',
            field=models.ManyToManyField(blank=True, related_name='messages', to='products.disease'),
        ),
        migrations.AlterField(
            model_name='message',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='messages', to='products.product'),
        ),
    ]
