# Generated by Django 5.2.5 on 2025-08-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_state_topic_state_alter_message_products_and_more'),
        ('products', '0005_disease_state_diseasecategory_state_product_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='products',
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='messages', to='products.productsku'),
        ),
    ]
