# Generated by Django 5.2.7 on 2026-03-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_diseases_alter_message_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_date']},
        ),
    ]
