# Generated by Django 5.2.5 on 2025-08-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_message_products_alter_message_text_and_more'),
        ('products', '0005_disease_state_diseasecategory_state_product_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='products',
            field=models.ManyToManyField(related_name='messages', to='products.productsku'),
        ),
    ]
