# Generated by Django 5.2.5 on 2025-08-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_phone_number_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='method',
            new_name='branch',
        ),
    ]
