# Generated by Django 5.2.7 on 2025-11-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated_date']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING'),
        ),
    ]
