name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Upload repository
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Connect to the server and deploy
      if: success()
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/boshadmin/IfodaBackend
          git fetch
          git reset --hard origin/main
          source .venv/bin/activate
          pip install -r requirements.txt
          python3 manage.py makemigrations
          python3 manage.py migrate
          sudo supervisorctl reread
          sudo supervisorctl update
          sudo supervisorctl restart IfodaBackend
          sudo systemctl restart nginx
