# Generated by Django 5.2.7 on 2025-11-11 05:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseasecategory',
            options={'verbose_name_plural': 'Disease Categories'},
        ),
        migrations.AlterField(
            model_name='disease',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.productsku'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
