# Generated by Django 5.2.5 on 2025-08-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_productcategory_productsku_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='product',
            field=models.ManyToManyField(to='products.productsku'),
        ),
    ]
