# Generated by Django 5.2.7 on 2025-12-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_diseasecategory_options_alter_disease_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsku',
            options={'ordering': ['-quantity'], 'verbose_name': 'Product SKU', 'verbose_name_plural': 'Product SKUs'},
        ),
    ]
