# Generated by Django 5.2.5 on 2025-08-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_disease_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diseasecategory',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsku',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diseases', to='products.diseasecategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='spic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='productSKU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='products.productsku'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_skus', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_subcategories', to='products.productcategory'),
        ),
    ]
