# Generated by Django 5.2.5 on 2025-08-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_disease_state_diseasecategory_state_product_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterModelOptions(
            name='productsku',
            options={'verbose_name_plural': 'Product SKUs'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name_plural': 'Product subcategories'},
        ),
    ]
