# Generated by Django 5.2.5 on 2025-09-20 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_disease_created_by_alter_disease_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='productSKU',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='products.product'),
        ),
    ]
