# Generated by Django 5.2.5 on 2025-09-20 05:52

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productimage_productsku_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
