# Generated by Django 5.2.5 on 2025-10-04 09:15

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_image_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsku',
            options={'verbose_name': 'Product SKU', 'verbose_name_plural': 'Product SKUs'},
        ),
        migrations.AddField(
            model_name='productsku',
            name='is_small_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product_thumbnails'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
